import type { SeedExercise } from './types.js';

export const cExercises: SeedExercise[] = [
  // =============================================
  // BEGINNER (7 exercises, 10 points each)
  // =============================================
  {
    title: 'Hola Mundo en C',
    slug: 'c-hola-mundo',
    description:
      'Escribe un programa en C que imprima exactamente el texto "Hola Mundo" en la salida estándar usando printf.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    // Tu codigo aqui',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    printf("Hola Mundo");',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '', expected: 'Hola Mundo' },
    ],
    tags: ['printf', 'salida', 'hola-mundo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Suma de dos enteros',
    slug: 'c-suma-dos-enteros',
    description:
      'Lee dos números enteros desde la entrada estándar separados por un espacio y muestra su suma.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    // Lee dos enteros y muestra su suma',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    printf("%d", a + b);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '3 5', expected: '8' },
      { input: '-2 7', expected: '5' },
      { input: '0 0', expected: '0' },
    ],
    tags: ['scanf', 'printf', 'suma', 'enteros'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Par o impar',
    slug: 'c-par-o-impar',
    description:
      'Lee un número entero e imprime "Par" si es par o "Impar" si es impar.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Determina si es par o impar',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    if (n % 2 == 0) {',
      '        printf("Par");',
      '    } else {',
      '        printf("Impar");',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '4', expected: 'Par' },
      { input: '7', expected: 'Impar' },
      { input: '0', expected: 'Par' },
      { input: '-3', expected: 'Impar' },
    ],
    tags: ['if-else', 'modulo', 'condicionales'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Valor absoluto',
    slug: 'c-valor-absoluto',
    description:
      'Lee un número entero desde la entrada estándar y muestra su valor absoluto. No uses la función abs() de la biblioteca estándar.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Imprime el valor absoluto de n',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    if (n < 0) n = -n;',
      '    printf("%d", n);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '-5', expected: '5' },
      { input: '3', expected: '3' },
      { input: '0', expected: '0' },
      { input: '-100', expected: '100' },
    ],
    tags: ['if', 'valor-absoluto', 'condicionales'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Mayor de tres números',
    slug: 'c-mayor-de-tres',
    description:
      'Lee tres números enteros separados por espacios e imprime el mayor de los tres.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b, c;',
      '    scanf("%d %d %d", &a, &b, &c);',
      '    // Imprime el mayor de los tres',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b, c;',
      '    scanf("%d %d %d", &a, &b, &c);',
      '    int max = a;',
      '    if (b > max) max = b;',
      '    if (c > max) max = c;',
      '    printf("%d", max);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '3 7 5', expected: '7' },
      { input: '10 2 8', expected: '10' },
      { input: '1 1 1', expected: '1' },
      { input: '-5 -2 -8', expected: '-2' },
    ],
    tags: ['if', 'comparacion', 'maximo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Área de un rectángulo',
    slug: 'c-area-rectangulo',
    description:
      'Lee dos enteros que representan la base y la altura de un rectángulo, e imprime su área.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int base, altura;',
      '    // Lee base y altura, imprime el area',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int base, altura;',
      '    scanf("%d %d", &base, &altura);',
      '    printf("%d", base * altura);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5 3', expected: '15' },
      { input: '10 10', expected: '100' },
      { input: '1 7', expected: '7' },
    ],
    tags: ['multiplicacion', 'area', 'geometria'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Intercambiar variables',
    slug: 'c-intercambiar-variables',
    description:
      'Lee dos enteros A y B, intercambia sus valores e imprime primero B y luego A separados por un espacio.',
    difficulty: 'beginner',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    // Intercambia a y b, luego imprime',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    int temp = a;',
      '    a = b;',
      '    b = temp;',
      '    printf("%d %d", a, b);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '3 5', expected: '5 3' },
      { input: '10 20', expected: '20 10' },
      { input: '-1 1', expected: '1 -1' },
    ],
    tags: ['variables', 'intercambio', 'temp'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  // =============================================
  // INTERMEDIATE (7 exercises, 25 points each)
  // =============================================
  {
    title: 'Tabla de multiplicar',
    slug: 'c-tabla-multiplicar',
    description:
      'Lee un número entero N e imprime su tabla de multiplicar del 1 al 10. Cada línea debe tener el formato "N x i = resultado". Ejemplo: "5 x 1 = 5".',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Imprime la tabla de multiplicar de n',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    for (int i = 1; i <= 10; i++) {',
      '        printf("%d x %d = %d\\n", n, i, n * i);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5', expected: '5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45\n5 x 10 = 50' },
      { input: '3', expected: '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30' },
    ],
    tags: ['for', 'bucles', 'tabla-multiplicar'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Factorial',
    slug: 'c-factorial',
    description:
      'Lee un número entero no negativo N e imprime su factorial (N!). Recuerda que 0! = 1.',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Calcula e imprime n!',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    long long fact = 1;',
      '    for (int i = 2; i <= n; i++) {',
      '        fact *= i;',
      '    }',
      '    printf("%lld", fact);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '0', expected: '1' },
      { input: '1', expected: '1' },
      { input: '5', expected: '120' },
      { input: '10', expected: '3628800' },
    ],
    tags: ['factorial', 'bucles', 'matematicas'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Invertir número',
    slug: 'c-invertir-numero',
    description:
      'Lee un número entero positivo e imprime sus dígitos en orden inverso. Por ejemplo, si la entrada es 1234, la salida es 4321.',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Invierte los digitos de n',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int rev = 0;',
      '    while (n > 0) {',
      '        rev = rev * 10 + n % 10;',
      '        n /= 10;',
      '    }',
      '    printf("%d", rev);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '1234', expected: '4321' },
      { input: '100', expected: '1' },
      { input: '5', expected: '5' },
      { input: '9876', expected: '6789' },
    ],
    tags: ['while', 'digitos', 'modulo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Contar vocales',
    slug: 'c-contar-vocales',
    description:
      'Lee una cadena de texto (máximo 100 caracteres, sin espacios) y cuenta cuántas vocales (a, e, i, o, u, mayúsculas o minúsculas) contiene. Imprime solo el número.',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '#include <string.h>',
      '',
      'int main() {',
      '    char s[101];',
      '    scanf("%s", s);',
      '    // Cuenta las vocales en s',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '#include <string.h>',
      '',
      'int main() {',
      '    char s[101];',
      '    scanf("%s", s);',
      '    int count = 0;',
      '    for (int i = 0; s[i]; i++) {',
      '        char c = s[i];',
      '        if (c==\'a\'||c==\'e\'||c==\'i\'||c==\'o\'||c==\'u\'||',
      '            c==\'A\'||c==\'E\'||c==\'I\'||c==\'O\'||c==\'U\') {',
      '            count++;',
      '        }',
      '    }',
      '    printf("%d", count);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: 'Hola', expected: '2' },
      { input: 'AEIOU', expected: '5' },
      { input: 'xyz', expected: '0' },
      { input: 'Murcielago', expected: '5' },
    ],
    tags: ['cadenas', 'vocales', 'for', 'condicionales'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Número primo',
    slug: 'c-numero-primo',
    description:
      'Lee un número entero positivo mayor que 1 y determina si es primo. Imprime "Si" si es primo o "No" si no lo es.',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Determina si n es primo',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    if (n < 2) { printf("No"); return 0; }',
      '    for (int i = 2; i * i <= n; i++) {',
      '        if (n % i == 0) { printf("No"); return 0; }',
      '    }',
      '    printf("Si");',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '7', expected: 'Si' },
      { input: '4', expected: 'No' },
      { input: '2', expected: 'Si' },
      { input: '25', expected: 'No' },
      { input: '13', expected: 'Si' },
    ],
    tags: ['primos', 'bucles', 'matematicas'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Suma de dígitos',
    slug: 'c-suma-digitos',
    description:
      'Lee un número entero positivo e imprime la suma de sus dígitos. Por ejemplo, para 1234 la salida es 10.',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Calcula la suma de los digitos de n',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int sum = 0;',
      '    while (n > 0) {',
      '        sum += n % 10;',
      '        n /= 10;',
      '    }',
      '    printf("%d", sum);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '1234', expected: '10' },
      { input: '9', expected: '9' },
      { input: '100', expected: '1' },
      { input: '999', expected: '27' },
    ],
    tags: ['digitos', 'while', 'modulo', 'suma'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Serie Fibonacci',
    slug: 'c-fibonacci',
    description:
      'Lee un entero N (N >= 1) e imprime los primeros N términos de la serie de Fibonacci separados por espacios. La serie empieza con 0, 1, 1, 2, 3, 5, ...',
    difficulty: 'intermediate',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    // Imprime los primeros n terminos de Fibonacci',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int a = 0, b = 1;',
      '    for (int i = 0; i < n; i++) {',
      '        if (i > 0) printf(" ");',
      '        printf("%d", a);',
      '        int temp = a + b;',
      '        a = b;',
      '        b = temp;',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '1', expected: '0' },
      { input: '5', expected: '0 1 1 2 3' },
      { input: '8', expected: '0 1 1 2 3 5 8 13' },
    ],
    tags: ['fibonacci', 'bucles', 'series'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  // =============================================
  // ADVANCED (6 exercises, 40 points each)
  // =============================================
  {
    title: 'Ordenamiento burbuja',
    slug: 'c-ordenamiento-burbuja',
    description:
      'Lee un entero N seguido de N enteros separados por espacios. Ordénalos de menor a mayor usando el algoritmo de burbuja e imprímelos separados por espacios.',
    difficulty: 'advanced',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int arr[100];',
      '    for (int i = 0; i < n; i++) scanf("%d", &arr[i]);',
      '    // Ordena arr usando burbuja e imprime',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int arr[100];',
      '    for (int i = 0; i < n; i++) scanf("%d", &arr[i]);',
      '    for (int i = 0; i < n - 1; i++) {',
      '        for (int j = 0; j < n - 1 - i; j++) {',
      '            if (arr[j] > arr[j+1]) {',
      '                int tmp = arr[j];',
      '                arr[j] = arr[j+1];',
      '                arr[j+1] = tmp;',
      '            }',
      '        }',
      '    }',
      '    for (int i = 0; i < n; i++) {',
      '        if (i > 0) printf(" ");',
      '        printf("%d", arr[i]);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5 3 1 4 1 5', expected: '1 1 3 4 5' },
      { input: '3 9 2 7', expected: '2 7 9' },
      { input: '4 -3 0 5 -1', expected: '-3 -1 0 5' },
    ],
    tags: ['arrays', 'ordenamiento', 'burbuja', 'algoritmos'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Búsqueda binaria',
    slug: 'c-busqueda-binaria',
    description:
      'Lee un entero N, luego N enteros ordenados de menor a mayor, y finalmente un entero X a buscar. Imprime el índice (base 0) donde se encuentra X, o -1 si no existe. Usa búsqueda binaria.',
    difficulty: 'advanced',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int arr[100];',
      '    for (int i = 0; i < n; i++) scanf("%d", &arr[i]);',
      '    int x;',
      '    scanf("%d", &x);',
      '    // Busca x en arr con busqueda binaria',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int arr[100];',
      '    for (int i = 0; i < n; i++) scanf("%d", &arr[i]);',
      '    int x;',
      '    scanf("%d", &x);',
      '    int lo = 0, hi = n - 1, result = -1;',
      '    while (lo <= hi) {',
      '        int mid = (lo + hi) / 2;',
      '        if (arr[mid] == x) { result = mid; break; }',
      '        else if (arr[mid] < x) lo = mid + 1;',
      '        else hi = mid - 1;',
      '    }',
      '    printf("%d", result);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5 1 3 5 7 9\n5', expected: '2' },
      { input: '5 1 3 5 7 9\n4', expected: '-1' },
      { input: '3 10 20 30\n30', expected: '2' },
      { input: '1 42\n42', expected: '0' },
    ],
    tags: ['busqueda-binaria', 'arrays', 'algoritmos'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Palíndromo de cadena',
    slug: 'c-palindromo-cadena',
    description:
      'Lee una cadena de texto (máximo 100 caracteres, sin espacios) y determina si es un palíndromo (se lee igual de izquierda a derecha y viceversa). Imprime "Si" o "No". La comparación debe ignorar mayúsculas/minúsculas.',
    difficulty: 'advanced',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '#include <string.h>',
      '',
      'int main() {',
      '    char s[101];',
      '    scanf("%s", s);',
      '    // Determina si s es palindromo',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '#include <string.h>',
      '',
      'int main() {',
      '    char s[101];',
      '    scanf("%s", s);',
      '    int len = strlen(s);',
      '    int ok = 1;',
      '    for (int i = 0; i < len / 2; i++) {',
      '        char a = s[i], b = s[len-1-i];',
      '        if (a >= \'A\' && a <= \'Z\') a += 32;',
      '        if (b >= \'A\' && b <= \'Z\') b += 32;',
      '        if (a != b) { ok = 0; break; }',
      '    }',
      '    printf(ok ? "Si" : "No");',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: 'Ana', expected: 'Si' },
      { input: 'hola', expected: 'No' },
      { input: 'reconocer', expected: 'Si' },
      { input: 'Aba', expected: 'Si' },
    ],
    tags: ['cadenas', 'palindromo', 'bucles'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Potencia recursiva',
    slug: 'c-potencia-recursiva',
    description:
      'Lee dos enteros: base y exponente (exponente >= 0). Calcula base^exponente usando una función recursiva e imprime el resultado. No uses la función pow().',
    difficulty: 'advanced',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'long long potencia(int base, int exp) {',
      '    // Implementa la funcion recursiva',
      '    return 0;',
      '}',
      '',
      'int main() {',
      '    int base, exp;',
      '    scanf("%d %d", &base, &exp);',
      '    printf("%lld", potencia(base, exp));',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'long long potencia(int base, int exp) {',
      '    if (exp == 0) return 1;',
      '    return base * potencia(base, exp - 1);',
      '}',
      '',
      'int main() {',
      '    int base, exp;',
      '    scanf("%d %d", &base, &exp);',
      '    printf("%lld", potencia(base, exp));',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '2 10', expected: '1024' },
      { input: '3 0', expected: '1' },
      { input: '5 3', expected: '125' },
      { input: '7 2', expected: '49' },
    ],
    tags: ['recursion', 'potencia', 'funciones'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Matriz transpuesta',
    slug: 'c-matriz-transpuesta',
    description:
      'Lee dos enteros M y N (filas y columnas), luego lee una matriz de M x N enteros. Imprime la matriz transpuesta (N x M). Cada fila en una línea, valores separados por espacios.',
    difficulty: 'advanced',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int m, n;',
      '    scanf("%d %d", &m, &n);',
      '    int mat[10][10];',
      '    for (int i = 0; i < m; i++)',
      '        for (int j = 0; j < n; j++)',
      '            scanf("%d", &mat[i][j]);',
      '    // Imprime la transpuesta',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int m, n;',
      '    scanf("%d %d", &m, &n);',
      '    int mat[10][10];',
      '    for (int i = 0; i < m; i++)',
      '        for (int j = 0; j < n; j++)',
      '            scanf("%d", &mat[i][j]);',
      '    for (int j = 0; j < n; j++) {',
      '        for (int i = 0; i < m; i++) {',
      '            if (i > 0) printf(" ");',
      '            printf("%d", mat[i][j]);',
      '        }',
      '        printf("\\n");',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '2 3 1 2 3 4 5 6', expected: '1 4\n2 5\n3 6' },
      { input: '3 2 1 2 3 4 5 6', expected: '1 3 5\n2 4 6' },
      { input: '1 3 7 8 9', expected: '7\n8\n9' },
    ],
    tags: ['matrices', 'transpuesta', 'arrays-2d'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'MCD y MCM',
    slug: 'c-mcd-mcm',
    description:
      'Lee dos enteros positivos A y B. Calcula su Máximo Común Divisor (MCD) usando el algoritmo de Euclides y su Mínimo Común Múltiplo (MCM). Imprime en una línea: "MCD MCM" separados por un espacio.',
    difficulty: 'advanced',
    languageSlug: 'c',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int mcd(int a, int b) {',
      '    // Implementa el algoritmo de Euclides',
      '    return 0;',
      '}',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    // Calcula e imprime MCD y MCM',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int mcd(int a, int b) {',
      '    while (b != 0) {',
      '        int t = b;',
      '        b = a % b;',
      '        a = t;',
      '    }',
      '    return a;',
      '}',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    int g = mcd(a, b);',
      '    int l = a / g * b;',
      '    printf("%d %d", g, l);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '12 8', expected: '4 24' },
      { input: '7 5', expected: '1 35' },
      { input: '100 25', expected: '25 100' },
      { input: '18 24', expected: '6 72' },
    ],
    tags: ['mcd', 'mcm', 'euclides', 'algoritmos', 'funciones'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
];
