import type { SeedExercise } from './types.js';

export const cppExercises: SeedExercise[] = [
  // =============================================
  // BEGINNER (5 exercises, 10 points each)
  // =============================================
  {
    title: 'Hola Mundo C++',
    slug: 'cpp-hola-mundo',
    description:
      'Escribe un programa en C que imprima exactamente el texto "Hola Mundo" en la salida estándar. Este es el primer paso para aprender a programar en C/C++.',
    difficulty: 'beginner',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    // Tu codigo aqui',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    printf("Hola Mundo");',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '', expected: 'Hola Mundo' },
    ],
    tags: ['printf', 'salida', 'hola-mundo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Suma de enteros',
    slug: 'cpp-suma-de-enteros',
    description:
      'Lee dos números enteros desde la entrada estándar y muestra su suma. La entrada contiene dos enteros separados por un espacio. Imprime únicamente el resultado de la suma.',
    difficulty: 'beginner',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    // Lee dos enteros y muestra su suma',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    printf("%d", a + b);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '3 5', expected: '8' },
      { input: '0 0', expected: '0' },
      { input: '-4 7', expected: '3' },
      { input: '100 200', expected: '300' },
    ],
    tags: ['scanf', 'suma', 'enteros', 'operadores'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Valor absoluto',
    slug: 'cpp-valor-absoluto',
    description:
      'Lee un número entero desde la entrada estándar e imprime su valor absoluto. Si el número es negativo, imprime el positivo correspondiente; si ya es positivo o cero, imprímelo tal cual.',
    difficulty: 'beginner',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee un entero e imprime su valor absoluto',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    if (n < 0) {',
      '        n = -n;',
      '    }',
      '    printf("%d", n);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '-5', expected: '5' },
      { input: '3', expected: '3' },
      { input: '0', expected: '0' },
      { input: '-100', expected: '100' },
    ],
    tags: ['condicional', 'valor-absoluto', 'if'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Mayor de tres',
    slug: 'cpp-mayor-de-tres',
    description:
      'Lee tres números enteros desde la entrada estándar (separados por espacios) e imprime el mayor de los tres.',
    difficulty: 'beginner',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b, c;',
      '    // Lee tres enteros e imprime el mayor',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b, c;',
      '    scanf("%d %d %d", &a, &b, &c);',
      '    int mayor = a;',
      '    if (b > mayor) {',
      '        mayor = b;',
      '    }',
      '    if (c > mayor) {',
      '        mayor = c;',
      '    }',
      '    printf("%d", mayor);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '1 2 3', expected: '3' },
      { input: '10 5 8', expected: '10' },
      { input: '-1 -2 -3', expected: '-1' },
      { input: '7 7 7', expected: '7' },
    ],
    tags: ['condicional', 'comparacion', 'maximo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },
  {
    title: 'Conversion de temperatura',
    slug: 'cpp-conversion-temperatura',
    description:
      'Lee una temperatura en grados Celsius (número decimal) desde la entrada estándar y muestra su equivalente en Fahrenheit con exactamente 2 decimales. La fórmula es: F = C * 9/5 + 32.',
    difficulty: 'beginner',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    float celsius;',
      '    // Lee temperatura en Celsius e imprime en Fahrenheit',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    float celsius;',
      '    scanf("%f", &celsius);',
      '    float fahrenheit = celsius * 9.0 / 5.0 + 32.0;',
      '    printf("%.2f", fahrenheit);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '0', expected: '32.00' },
      { input: '100', expected: '212.00' },
      { input: '-40', expected: '-40.00' },
      { input: '37', expected: '98.60' },
    ],
    tags: ['float', 'conversion', 'formula', 'printf'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  // =============================================
  // BASIC (5 exercises, 15 points each)
  // =============================================
  {
    title: 'Tabla de multiplicar',
    slug: 'cpp-tabla-de-multiplicar',
    description:
      'Lee un número entero n desde la entrada estándar e imprime su tabla de multiplicar del 1 al 10. Cada línea debe tener el formato: "n x i = resultado" (donde i va de 1 a 10).',
    difficulty: 'basic',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee n e imprime su tabla de multiplicar',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int i;',
      '    for (i = 1; i <= 10; i++) {',
      '        printf("%d x %d = %d\\n", n, i, n * i);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      {
        input: '5',
        expected:
          '5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45\n5 x 10 = 50',
      },
      {
        input: '3',
        expected:
          '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27\n3 x 10 = 30',
      },
      {
        input: '1',
        expected:
          '1 x 1 = 1\n1 x 2 = 2\n1 x 3 = 3\n1 x 4 = 4\n1 x 5 = 5\n1 x 6 = 6\n1 x 7 = 7\n1 x 8 = 8\n1 x 9 = 9\n1 x 10 = 10',
      },
    ],
    tags: ['bucle', 'for', 'multiplicacion', 'tabla'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },
  {
    title: 'Contar digitos',
    slug: 'cpp-contar-digitos',
    description:
      'Lee un número entero positivo desde la entrada estándar y muestra la cantidad de dígitos que tiene. Por ejemplo, 1234 tiene 4 dígitos. El número siempre será mayor o igual a 1.',
    difficulty: 'basic',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee un entero positivo y cuenta sus digitos',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int count = 0;',
      '    while (n > 0) {',
      '        n = n / 10;',
      '        count++;',
      '    }',
      '    printf("%d", count);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '1234', expected: '4' },
      { input: '7', expected: '1' },
      { input: '100', expected: '3' },
      { input: '999999', expected: '6' },
    ],
    tags: ['bucle', 'while', 'digitos', 'division'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },
  {
    title: 'Potencia',
    slug: 'cpp-potencia',
    description:
      'Lee dos números enteros: una base y un exponente (exponente >= 0). Calcula e imprime el resultado de base elevado al exponente sin usar funciones de biblioteca. Usa un bucle para multiplicar.',
    difficulty: 'basic',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int base, exp;',
      '    // Lee base y exponente, calcula base^exp',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int base, exp;',
      '    scanf("%d %d", &base, &exp);',
      '    int result = 1;',
      '    int i;',
      '    for (i = 0; i < exp; i++) {',
      '        result = result * base;',
      '    }',
      '    printf("%d", result);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '2 10', expected: '1024' },
      { input: '3 4', expected: '81' },
      { input: '5 0', expected: '1' },
      { input: '7 2', expected: '49' },
    ],
    tags: ['bucle', 'potencia', 'multiplicacion'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },
  {
    title: 'MCD',
    slug: 'cpp-mcd',
    description:
      'Lee dos números enteros positivos desde la entrada estándar y calcula su Máximo Común Divisor (MCD) usando el algoritmo de Euclides. Imprime el resultado.',
    difficulty: 'basic',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    // Lee dos enteros y calcula el MCD',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    while (b != 0) {',
      '        int temp = b;',
      '        b = a % b;',
      '        a = temp;',
      '    }',
      '    printf("%d", a);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '12 8', expected: '4' },
      { input: '100 75', expected: '25' },
      { input: '7 13', expected: '1' },
      { input: '36 24', expected: '12' },
    ],
    tags: ['euclides', 'mcd', 'modulo', 'while'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },
  {
    title: 'Numeros pares',
    slug: 'cpp-numeros-pares',
    description:
      'Lee un número entero n (n >= 2) desde la entrada estándar e imprime todos los números pares desde 2 hasta n (inclusive, si n es par) separados por un espacio. No debe haber espacio al final de la línea.',
    difficulty: 'basic',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee n e imprime los pares de 2 a n',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int first = 1;',
      '    int i;',
      '    for (i = 2; i <= n; i = i + 2) {',
      '        if (first) {',
      '            first = 0;',
      '        } else {',
      '            printf(" ");',
      '        }',
      '        printf("%d", i);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '10', expected: '2 4 6 8 10' },
      { input: '7', expected: '2 4 6' },
      { input: '2', expected: '2' },
      { input: '20', expected: '2 4 6 8 10 12 14 16 18 20' },
    ],
    tags: ['bucle', 'pares', 'for', 'modulo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },

  // =============================================
  // INTERMEDIATE (5 exercises, 25 points each)
  // =============================================
  {
    title: 'Numero primo',
    slug: 'cpp-numero-primo',
    description:
      'Lee un número entero n (n >= 2) desde la entrada estándar y determina si es primo. Imprime "Si" si es primo, o "No" si no lo es. Un número primo solo es divisible por 1 y por sí mismo.',
    difficulty: 'intermediate',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee n y determina si es primo',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int es_primo = 1;',
      '    if (n < 2) {',
      '        es_primo = 0;',
      '    } else {',
      '        int i;',
      '        for (i = 2; i * i <= n; i++) {',
      '            if (n % i == 0) {',
      '                es_primo = 0;',
      '                break;',
      '            }',
      '        }',
      '    }',
      '    if (es_primo) {',
      '        printf("Si");',
      '    } else {',
      '        printf("No");',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '7', expected: 'Si' },
      { input: '4', expected: 'No' },
      { input: '2', expected: 'Si' },
      { input: '97', expected: 'Si' },
      { input: '100', expected: 'No' },
    ],
    tags: ['primo', 'bucle', 'condicional', 'matematicas'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Burbuja',
    slug: 'cpp-burbuja',
    description:
      'Implementa el algoritmo de ordenamiento burbuja. Lee un entero n (cantidad de elementos) seguido de n enteros. Ordena los números de menor a mayor e imprímelos separados por espacios. No debe haber espacio al final.',
    difficulty: 'intermediate',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    // Lee n elementos, ordenalos con burbuja e imprime',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    scanf("%d", &n);',
      '    int i;',
      '    for (i = 0; i < n; i++) {',
      '        scanf("%d", &arr[i]);',
      '    }',
      '    int j;',
      '    for (i = 0; i < n - 1; i++) {',
      '        for (j = 0; j < n - 1 - i; j++) {',
      '            if (arr[j] > arr[j + 1]) {',
      '                int temp = arr[j];',
      '                arr[j] = arr[j + 1];',
      '                arr[j + 1] = temp;',
      '            }',
      '        }',
      '    }',
      '    for (i = 0; i < n; i++) {',
      '        if (i > 0) {',
      '            printf(" ");',
      '        }',
      '        printf("%d", arr[i]);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5\n5 3 1 4 2', expected: '1 2 3 4 5' },
      { input: '4\n10 -1 3 7', expected: '-1 3 7 10' },
      { input: '3\n1 2 3', expected: '1 2 3' },
      { input: '6\n9 8 7 6 5 4', expected: '4 5 6 7 8 9' },
    ],
    tags: ['ordenamiento', 'burbuja', 'array', 'bucle'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Patron triangular',
    slug: 'cpp-patron-triangular',
    description:
      'Lee un entero n e imprime un triángulo de números alineado a la derecha. La fila i (empezando en 1) contiene los números del 1 al i, precedidos por espacios para alinear a la derecha. Cada número ocupa un carácter y está separado por un espacio de los demás. La última fila no tiene espacios iniciales.',
    difficulty: 'intermediate',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee n e imprime el patron triangular',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int i, j;',
      '    for (i = 1; i <= n; i++) {',
      '        int spaces = (n - i) * 2;',
      '        for (j = 0; j < spaces; j++) {',
      '            printf(" ");',
      '        }',
      '        for (j = 1; j <= i; j++) {',
      '            if (j > 1) {',
      '                printf(" ");',
      '            }',
      '            printf("%d", j);',
      '        }',
      '        printf("\\n");',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      {
        input: '4',
        expected: '      1\n    1 2\n  1 2 3\n1 2 3 4',
      },
      {
        input: '3',
        expected: '    1\n  1 2\n1 2 3',
      },
      {
        input: '1',
        expected: '1',
      },
    ],
    tags: ['patron', 'bucle-anidado', 'printf', 'espacios'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Suma de array',
    slug: 'cpp-suma-de-array',
    description:
      'Lee un entero n (cantidad de elementos), luego lee n enteros y calcula la suma de todos ellos. Imprime el resultado.',
    difficulty: 'intermediate',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    // Lee n enteros en un array y calcula la suma',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    scanf("%d", &n);',
      '    int sum = 0;',
      '    int i;',
      '    for (i = 0; i < n; i++) {',
      '        scanf("%d", &arr[i]);',
      '        sum = sum + arr[i];',
      '    }',
      '    printf("%d", sum);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5\n1 2 3 4 5', expected: '15' },
      { input: '3\n10 20 30', expected: '60' },
      { input: '4\n-1 -2 3 4', expected: '4' },
      { input: '1\n42', expected: '42' },
    ],
    tags: ['array', 'suma', 'bucle', 'scanf'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },
  {
    title: 'Busqueda lineal',
    slug: 'cpp-busqueda-lineal',
    description:
      'Implementa búsqueda lineal. Lee un entero n, luego n enteros que forman un array, y finalmente un número objetivo. Imprime el índice (basado en 0) de la primera aparición del objetivo en el array, o -1 si no se encuentra.',
    difficulty: 'intermediate',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    int target;',
      '    // Lee el array y el objetivo, busca e imprime el indice',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    int target;',
      '    scanf("%d", &n);',
      '    int i;',
      '    for (i = 0; i < n; i++) {',
      '        scanf("%d", &arr[i]);',
      '    }',
      '    scanf("%d", &target);',
      '    int found = -1;',
      '    for (i = 0; i < n; i++) {',
      '        if (arr[i] == target) {',
      '            found = i;',
      '            break;',
      '        }',
      '    }',
      '    printf("%d", found);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5\n10 20 30 40 50\n30', expected: '2' },
      { input: '4\n1 2 3 4\n5', expected: '-1' },
      { input: '6\n5 3 5 7 5 9\n5', expected: '0' },
      { input: '3\n100 200 300\n200', expected: '1' },
    ],
    tags: ['busqueda', 'lineal', 'array', 'indice'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  // =============================================
  // ADVANCED (5 exercises, 40 points each)
  // =============================================
  {
    title: 'Matriz multiplicacion',
    slug: 'cpp-matriz-multiplicacion',
    description:
      'Lee dos matrices de 2x2 e imprime su producto. La entrada tiene 8 enteros: los primeros 4 son la matriz A (fila por fila) y los siguientes 4 son la matriz B. Imprime la matriz resultante en dos líneas, con los valores separados por espacio.',
    difficulty: 'advanced',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a[2][2], b[2][2], c[2][2];',
      '    // Lee dos matrices 2x2 e imprime su producto',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a[2][2], b[2][2], c[2][2];',
      '    int i, j, k;',
      '    for (i = 0; i < 2; i++) {',
      '        for (j = 0; j < 2; j++) {',
      '            scanf("%d", &a[i][j]);',
      '        }',
      '    }',
      '    for (i = 0; i < 2; i++) {',
      '        for (j = 0; j < 2; j++) {',
      '            scanf("%d", &b[i][j]);',
      '        }',
      '    }',
      '    for (i = 0; i < 2; i++) {',
      '        for (j = 0; j < 2; j++) {',
      '            c[i][j] = 0;',
      '            for (k = 0; k < 2; k++) {',
      '                c[i][j] = c[i][j] + a[i][k] * b[k][j];',
      '            }',
      '        }',
      '    }',
      '    for (i = 0; i < 2; i++) {',
      '        for (j = 0; j < 2; j++) {',
      '            if (j > 0) {',
      '                printf(" ");',
      '            }',
      '            printf("%d", c[i][j]);',
      '        }',
      '        printf("\\n");',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      {
        input: '1 2 3 4\n5 6 7 8',
        expected: '19 22\n43 50',
      },
      {
        input: '1 0 0 1\n5 6 7 8',
        expected: '5 6\n7 8',
      },
      {
        input: '2 0 0 2\n3 4 5 6',
        expected: '6 8\n10 12',
      },
    ],
    tags: ['matriz', 'multiplicacion', 'bucle-anidado', 'array-2d'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Numeros Armstrong',
    slug: 'cpp-numeros-armstrong',
    description:
      'Lee dos enteros a y b que definen un rango [a, b]. Encuentra e imprime todos los números Armstrong en ese rango, uno por línea. Un número Armstrong de n dígitos es aquel donde la suma de cada dígito elevado a la n-ésima potencia es igual al número. Ejemplo: 153 = 1^3 + 5^3 + 3^3. Si no hay ninguno, no imprimas nada.',
    difficulty: 'advanced',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    // Lee rango [a,b] e imprime numeros Armstrong',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int a, b;',
      '    scanf("%d %d", &a, &b);',
      '    int num;',
      '    for (num = a; num <= b; num++) {',
      '        int temp = num;',
      '        int digits = 0;',
      '        while (temp > 0) {',
      '            digits++;',
      '            temp = temp / 10;',
      '        }',
      '        if (num == 0) {',
      '            printf("0\\n");',
      '            continue;',
      '        }',
      '        temp = num;',
      '        int sum = 0;',
      '        while (temp > 0) {',
      '            int d = temp % 10;',
      '            int power = 1;',
      '            int p;',
      '            for (p = 0; p < digits; p++) {',
      '                power = power * d;',
      '            }',
      '            sum = sum + power;',
      '            temp = temp / 10;',
      '        }',
      '        if (sum == num) {',
      '            printf("%d\\n", num);',
      '        }',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      {
        input: '1 500',
        expected: '1\n2\n3\n4\n5\n6\n7\n8\n9\n153\n370\n371\n407',
      },
      {
        input: '100 400',
        expected: '153\n370\n371',
      },
      {
        input: '400 10000',
        expected: '407\n1634\n8208\n9474',
      },
    ],
    tags: ['armstrong', 'digitos', 'potencia', 'bucle'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Conversion binaria',
    slug: 'cpp-conversion-binaria',
    description:
      'Lee un número entero decimal positivo (mayor que 0) desde la entrada estándar y muestra su representación en binario. No uses ceros a la izquierda. Por ejemplo, 10 en binario es 1010.',
    difficulty: 'advanced',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    // Lee un decimal e imprime su representacion binaria',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    scanf("%d", &n);',
      '    int bits[32];',
      '    int count = 0;',
      '    while (n > 0) {',
      '        bits[count] = n % 2;',
      '        n = n / 2;',
      '        count++;',
      '    }',
      '    int i;',
      '    for (i = count - 1; i >= 0; i--) {',
      '        printf("%d", bits[i]);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '10', expected: '1010' },
      { input: '1', expected: '1' },
      { input: '255', expected: '11111111' },
      { input: '42', expected: '101010' },
      { input: '128', expected: '10000000' },
    ],
    tags: ['binario', 'conversion', 'modulo', 'array'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Serie de potencias',
    slug: 'cpp-serie-de-potencias',
    description:
      'Lee dos valores: un número decimal x y un entero n. Calcula una aproximación de e^x usando los primeros n términos de la serie de Taylor: e^x = 1 + x/1! + x^2/2! + x^3/3! + ... Imprime el resultado con exactamente 4 decimales.',
    difficulty: 'advanced',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    double x;',
      '    int n;',
      '    // Calcula e^x usando n terminos de Taylor',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    double x;',
      '    int n;',
      '    scanf("%lf %d", &x, &n);',
      '    double sum = 0.0;',
      '    double term = 1.0;',
      '    int i;',
      '    for (i = 0; i < n; i++) {',
      '        sum = sum + term;',
      '        term = term * x / (i + 1);',
      '    }',
      '    printf("%.4f", sum);',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '1.0 10', expected: '2.7183' },
      { input: '0.0 5', expected: '1.0000' },
      { input: '2.0 15', expected: '7.3891' },
      { input: '1.0 1', expected: '1.0000' },
    ],
    tags: ['taylor', 'serie', 'factorial', 'double', 'aproximacion'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
  {
    title: 'Ordenamiento seleccion',
    slug: 'cpp-ordenamiento-seleccion',
    description:
      'Implementa el algoritmo de ordenamiento por selección. Lee un entero n seguido de n enteros. Ordena los números de menor a mayor usando el algoritmo de selección e imprímelos separados por espacios. No debe haber espacio al final.',
    difficulty: 'advanced',
    languageSlug: 'cpp',
    starterCode: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    // Lee n elementos, ordena por seleccion e imprime',
      '    return 0;',
      '}',
    ].join('\n'),
    solution: [
      '#include <stdio.h>',
      '',
      'int main() {',
      '    int n;',
      '    int arr[100];',
      '    scanf("%d", &n);',
      '    int i;',
      '    for (i = 0; i < n; i++) {',
      '        scanf("%d", &arr[i]);',
      '    }',
      '    int j;',
      '    for (i = 0; i < n - 1; i++) {',
      '        int min_idx = i;',
      '        for (j = i + 1; j < n; j++) {',
      '            if (arr[j] < arr[min_idx]) {',
      '                min_idx = j;',
      '            }',
      '        }',
      '        if (min_idx != i) {',
      '            int temp = arr[i];',
      '            arr[i] = arr[min_idx];',
      '            arr[min_idx] = temp;',
      '        }',
      '    }',
      '    for (i = 0; i < n; i++) {',
      '        if (i > 0) {',
      '            printf(" ");',
      '        }',
      '        printf("%d", arr[i]);',
      '    }',
      '    return 0;',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5\n64 25 12 22 11', expected: '11 12 22 25 64' },
      { input: '4\n4 3 2 1', expected: '1 2 3 4' },
      { input: '6\n-5 3 0 -1 7 2', expected: '-5 -1 0 2 3 7' },
      { input: '3\n1 1 1', expected: '1 1 1' },
    ],
    tags: ['ordenamiento', 'seleccion', 'array', 'bucle-anidado'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
];
