import type { SeedExercise } from './types.js';

export const jsExercises: SeedExercise[] = [
  // ─────────────────────────────────────────────
  // BEGINNER (5 exercises, 10 points each)
  // ─────────────────────────────────────────────

  {
    title: 'Hola Mundo JS',
    slug: 'js-hola-mundo',
    description:
      'Escribe un programa que imprima exactamente "Hola Mundo" en la consola. Este es el primer paso de todo programador.',
    difficulty: 'beginner',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Hola Mundo JS',
      '// Imprime "Hola Mundo" en la consola.',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: 'console.log("Hola Mundo");',
    testCases: [
      { input: '', expected: 'Hola Mundo' },
      { input: '', expected: 'Hola Mundo' },
      { input: '', expected: 'Hola Mundo' },
    ],
    tags: ['console.log', 'hola-mundo', 'fundamentos'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  {
    title: 'Suma de dos números',
    slug: 'js-suma-dos-numeros',
    description:
      'Lee dos números enteros mediante prompt() e imprime su suma. Cada número se lee en una línea separada.',
    difficulty: 'beginner',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Suma de dos números',
      '// Lee dos números con prompt() e imprime su suma.',
      '',
      'const a = prompt();',
      'const b = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const a = Number(prompt());',
      'const b = Number(prompt());',
      'console.log(a + b);',
    ].join('\n'),
    testCases: [
      { input: '3\n5', expected: '8' },
      { input: '0\n0', expected: '0' },
      { input: '-4\n7', expected: '3' },
      { input: '100\n200', expected: '300' },
    ],
    tags: ['prompt', 'Number', 'suma', 'operadores'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  {
    title: 'Tipo de dato',
    slug: 'js-tipo-de-dato',
    description:
      'Lee un valor mediante prompt(). Si el valor puede convertirse a número (y no es vacío), imprime "numero". Si es "true" o "false", imprime "booleano". En cualquier otro caso, imprime "texto".',
    difficulty: 'beginner',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Tipo de dato',
      '// Lee un valor con prompt() y determina si es "numero", "booleano" o "texto".',
      '',
      'const valor = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const valor = prompt();',
      'if (valor === "true" || valor === "false") {',
      '  console.log("booleano");',
      '} else if (valor.trim() !== "" && !isNaN(Number(valor))) {',
      '  console.log("numero");',
      '} else {',
      '  console.log("texto");',
      '}',
    ].join('\n'),
    testCases: [
      { input: '42', expected: 'numero' },
      { input: 'true', expected: 'booleano' },
      { input: 'hola', expected: 'texto' },
      { input: 'false', expected: 'booleano' },
      { input: '3.14', expected: 'numero' },
    ],
    tags: ['typeof', 'condicionales', 'tipos-de-dato'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  {
    title: 'Concatenar nombres',
    slug: 'js-concatenar-nombres',
    description:
      'Lee el nombre y el apellido de una persona (cada uno en una línea) e imprime el saludo: "Hola, [nombre] [apellido]!"',
    difficulty: 'beginner',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Concatenar nombres',
      '// Lee nombre y apellido con prompt() e imprime "Hola, [nombre] [apellido]!"',
      '',
      'const nombre = prompt();',
      'const apellido = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const nombre = prompt();',
      'const apellido = prompt();',
      'console.log(`Hola, ${nombre} ${apellido}!`);',
    ].join('\n'),
    testCases: [
      { input: 'Juan\nPérez', expected: 'Hola, Juan Pérez!' },
      { input: 'María\nGómez', expected: 'Hola, María Gómez!' },
      { input: 'Ana\nLópez', expected: 'Hola, Ana López!' },
      { input: 'Carlos\nRuiz', expected: 'Hola, Carlos Ruiz!' },
    ],
    tags: ['template-literals', 'concatenación', 'strings'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  {
    title: 'Celsius a Fahrenheit',
    slug: 'js-celsius-fahrenheit',
    description:
      'Lee una temperatura en grados Celsius mediante prompt() y conviértela a Fahrenheit usando la fórmula: F = C * 9/5 + 32. Imprime el resultado redondeado a 2 decimales.',
    difficulty: 'beginner',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Celsius a Fahrenheit',
      '// Lee grados Celsius con prompt() e imprime la conversión a Fahrenheit.',
      '// Fórmula: F = C * 9/5 + 32',
      '',
      'const celsius = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const celsius = Number(prompt());',
      'const fahrenheit = celsius * 9 / 5 + 32;',
      'console.log(parseFloat(fahrenheit.toFixed(2)));',
    ].join('\n'),
    testCases: [
      { input: '0', expected: '32' },
      { input: '100', expected: '212' },
      { input: '-40', expected: '-40' },
      { input: '37', expected: '98.6' },
    ],
    tags: ['matemáticas', 'conversión', 'Number'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 10,
    isActive: true,
  },

  // ─────────────────────────────────────────────
  // BASIC (5 exercises, 15 points each)
  // ─────────────────────────────────────────────

  {
    title: 'FizzBuzz',
    slug: 'js-fizzbuzz',
    description:
      'Lee un número n. Para cada número del 1 al n: si es divisible entre 3 y 5 imprime "FizzBuzz", si solo entre 3 imprime "Fizz", si solo entre 5 imprime "Buzz", de lo contrario imprime el número.',
    difficulty: 'basic',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: FizzBuzz',
      '// Lee n con prompt() e imprime FizzBuzz del 1 al n.',
      '',
      'const n = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const n = Number(prompt());',
      'for (let i = 1; i <= n; i++) {',
      '  if (i % 15 === 0) console.log("FizzBuzz");',
      '  else if (i % 3 === 0) console.log("Fizz");',
      '  else if (i % 5 === 0) console.log("Buzz");',
      '  else console.log(i);',
      '}',
    ].join('\n'),
    testCases: [
      { input: '5', expected: '1\n2\nFizz\n4\nBuzz' },
      { input: '15', expected: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz' },
      { input: '3', expected: '1\n2\nFizz' },
      { input: '1', expected: '1' },
    ],
    tags: ['bucles', 'condicionales', 'módulo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },

  {
    title: 'Contar palabras',
    slug: 'js-contar-palabras',
    description:
      'Lee una oración mediante prompt() e imprime la cantidad de palabras que contiene. Las palabras están separadas por uno o más espacios.',
    difficulty: 'basic',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Contar palabras',
      '// Lee una oración con prompt() e imprime el número de palabras.',
      '',
      'const oracion = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const oracion = prompt();',
      'const palabras = oracion.trim().split(/\\s+/);',
      'console.log(oracion.trim() === "" ? 0 : palabras.length);',
    ].join('\n'),
    testCases: [
      { input: 'Hola mundo cruel', expected: '3' },
      { input: 'JavaScript', expected: '1' },
      { input: 'uno  dos   tres', expected: '3' },
      { input: 'a b c d e f', expected: '6' },
    ],
    tags: ['strings', 'split', 'regex'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },

  {
    title: 'Array invertido',
    slug: 'js-array-invertido',
    description:
      'Lee un número n, luego lee n números (uno por línea). Imprime los números en orden inverso, separados por espacios en una sola línea.',
    difficulty: 'basic',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Array invertido',
      '// Lee n, luego n números, e imprime los números invertidos separados por espacios.',
      '',
      'const n = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const n = Number(prompt());',
      'const arr = [];',
      'for (let i = 0; i < n; i++) {',
      '  arr.push(prompt());',
      '}',
      'console.log(arr.reverse().join(" "));',
    ].join('\n'),
    testCases: [
      { input: '3\n1\n2\n3', expected: '3 2 1' },
      { input: '5\n10\n20\n30\n40\n50', expected: '50 40 30 20 10' },
      { input: '1\n42', expected: '42' },
      { input: '4\na\nb\nc\nd', expected: 'd c b a' },
    ],
    tags: ['arrays', 'reverse', 'bucles'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },

  {
    title: 'Número perfecto',
    slug: 'js-numero-perfecto',
    description:
      'Lee un número entero positivo e indica si es un número perfecto. Un número perfecto es igual a la suma de sus divisores propios (excluyéndose a sí mismo). Imprime "Si" o "No".',
    difficulty: 'basic',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Número perfecto',
      '// Lee un número con prompt() e imprime "Si" si es perfecto, "No" en caso contrario.',
      '// Un número perfecto = suma de sus divisores propios.',
      '',
      'const num = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const num = Number(prompt());',
      'let suma = 0;',
      'for (let i = 1; i < num; i++) {',
      '  if (num % i === 0) suma += i;',
      '}',
      'console.log(suma === num ? "Si" : "No");',
    ].join('\n'),
    testCases: [
      { input: '6', expected: 'Si' },
      { input: '28', expected: 'Si' },
      { input: '12', expected: 'No' },
      { input: '496', expected: 'Si' },
      { input: '10', expected: 'No' },
    ],
    tags: ['matemáticas', 'divisores', 'bucles'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },

  {
    title: 'Triángulo de asteriscos',
    slug: 'js-triangulo-asteriscos',
    description:
      'Lee un número n e imprime un triángulo rectángulo de asteriscos con n filas. La primera fila tiene 1 asterisco, la segunda 2, y así sucesivamente.',
    difficulty: 'basic',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Triángulo de asteriscos',
      '// Lee n con prompt() e imprime un triángulo de n filas de asteriscos.',
      '',
      'const n = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const n = Number(prompt());',
      'for (let i = 1; i <= n; i++) {',
      '  console.log("*".repeat(i));',
      '}',
    ].join('\n'),
    testCases: [
      { input: '3', expected: '*\n**\n***' },
      { input: '5', expected: '*\n**\n***\n****\n*****' },
      { input: '1', expected: '*' },
      { input: '4', expected: '*\n**\n***\n****' },
    ],
    tags: ['bucles', 'strings', 'patrones'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 15,
    isActive: true,
  },

  // ─────────────────────────────────────────────
  // INTERMEDIATE (5 exercises, 25 points each)
  // ─────────────────────────────────────────────

  {
    title: 'Anagrama',
    slug: 'js-anagrama',
    description:
      'Lee dos cadenas de texto (una por línea) y determina si son anagramas entre sí. Ignora mayúsculas y minúsculas. Imprime "Si" o "No". Dos palabras son anagramas si contienen exactamente las mismas letras con la misma frecuencia.',
    difficulty: 'intermediate',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Anagrama',
      '// Lee dos cadenas con prompt() y determina si son anagramas.',
      '// Ignora mayúsculas/minúsculas. Imprime "Si" o "No".',
      '',
      'const str1 = prompt();',
      'const str2 = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const str1 = prompt().toLowerCase().split("").sort().join("");',
      'const str2 = prompt().toLowerCase().split("").sort().join("");',
      'console.log(str1 === str2 ? "Si" : "No");',
    ].join('\n'),
    testCases: [
      { input: 'Roma\nMora', expected: 'Si' },
      { input: 'listen\nsilent', expected: 'Si' },
      { input: 'hola\nmundo', expected: 'No' },
      { input: 'Fresa\nFrase', expected: 'Si' },
      { input: 'abc\nabcd', expected: 'No' },
    ],
    tags: ['strings', 'sort', 'anagrama'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  {
    title: 'Frecuencia de caracteres',
    slug: 'js-frecuencia-caracteres',
    description:
      'Lee una cadena de texto e imprime la frecuencia de cada carácter (sin contar espacios), uno por línea en formato "c:N", ordenados alfabéticamente por el carácter. Los caracteres se consideran en minúsculas.',
    difficulty: 'intermediate',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Frecuencia de caracteres',
      '// Lee una cadena con prompt() e imprime la frecuencia de cada carácter.',
      '// Formato: "c:N" por línea, ordenado alfabéticamente. Ignora espacios.',
      '',
      'const texto = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const texto = prompt().toLowerCase();',
      'const freq = {};',
      'for (const c of texto) {',
      '  if (c === " ") continue;',
      '  freq[c] = (freq[c] || 0) + 1;',
      '}',
      'const sorted = Object.keys(freq).sort();',
      'for (const k of sorted) {',
      '  console.log(`${k}:${freq[k]}`);',
      '}',
    ].join('\n'),
    testCases: [
      { input: 'hola', expected: 'a:1\nh:1\nl:1\no:1' },
      { input: 'banana', expected: 'a:3\nb:1\nn:2' },
      { input: 'Aba', expected: 'a:2\nb:1' },
      { input: 'hola mundo', expected: 'a:1\nd:1\nh:1\nl:1\nm:1\nn:1\no:2\nu:1' },
    ],
    tags: ['objetos', 'strings', 'frecuencia', 'sort'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  {
    title: 'Números únicos',
    slug: 'js-numeros-unicos',
    description:
      'Lee un número n, luego lee n números enteros (uno por línea). Imprime únicamente los números que aparecen exactamente una vez, en el orden en que fueron ingresados, separados por espacios.',
    difficulty: 'intermediate',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Números únicos',
      '// Lee n, luego n números. Imprime solo los que aparecen una vez, en orden original.',
      '',
      'const n = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const n = Number(prompt());',
      'const nums = [];',
      'for (let i = 0; i < n; i++) {',
      '  nums.push(prompt());',
      '}',
      'const count = {};',
      'for (const x of nums) {',
      '  count[x] = (count[x] || 0) + 1;',
      '}',
      'const result = nums.filter(x => count[x] === 1);',
      'console.log(result.join(" "));',
    ].join('\n'),
    testCases: [
      { input: '5\n1\n2\n3\n2\n1', expected: '3' },
      { input: '4\n4\n5\n6\n7', expected: '4 5 6 7' },
      { input: '6\n1\n1\n2\n2\n3\n3', expected: '' },
      { input: '7\n10\n20\n10\n30\n20\n40\n50', expected: '30 40 50' },
    ],
    tags: ['arrays', 'objetos', 'filter', 'frecuencia'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  {
    title: 'Calculadora RPN',
    slug: 'js-calculadora-rpn',
    description:
      'Lee una expresión en Notación Polaca Inversa (RPN) como una sola línea con tokens separados por espacios. Los operadores soportados son +, -, * y /. La división es entera (truncada hacia cero). Imprime el resultado final.',
    difficulty: 'intermediate',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Calculadora RPN',
      '// Lee una expresión en Notación Polaca Inversa con prompt().',
      '// Operadores: + - * /  (división entera truncada hacia cero)',
      '// Imprime el resultado.',
      '',
      'const expresion = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const tokens = prompt().split(" ");',
      'const stack = [];',
      'for (const t of tokens) {',
      '  if ("+-*/".includes(t) && t.length === 1) {',
      '    const b = stack.pop();',
      '    const a = stack.pop();',
      '    if (t === "+") stack.push(a + b);',
      '    else if (t === "-") stack.push(a - b);',
      '    else if (t === "*") stack.push(a * b);',
      '    else stack.push(Math.trunc(a / b));',
      '  } else {',
      '    stack.push(Number(t));',
      '  }',
      '}',
      'console.log(stack[0]);',
    ].join('\n'),
    testCases: [
      { input: '3 4 +', expected: '7' },
      { input: '5 1 2 + 4 * + 3 -', expected: '14' },
      { input: '2 3 * 4 +', expected: '10' },
      { input: '10 3 /', expected: '3' },
      { input: '15 7 1 1 + - / 3 * 2 1 1 + + -', expected: '5' },
    ],
    tags: ['stack', 'RPN', 'algoritmos'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  {
    title: 'Cifrado César',
    slug: 'js-cifrado-cesar',
    description:
      'Lee una cadena de texto y un número de desplazamiento (shift). Aplica el cifrado César solo a letras (a-z, A-Z), preservando mayúsculas/minúsculas y dejando los demás caracteres sin cambios. Imprime la cadena cifrada.',
    difficulty: 'intermediate',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Cifrado César',
      '// Lee una cadena y un shift con prompt().',
      '// Aplica cifrado César solo a letras, preserva mayúsculas/minúsculas.',
      '',
      'const texto = prompt();',
      'const shift = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const texto = prompt();',
      'const shift = ((Number(prompt()) % 26) + 26) % 26;',
      'let result = "";',
      'for (const c of texto) {',
      '  const code = c.charCodeAt(0);',
      '  if (code >= 65 && code <= 90) {',
      '    result += String.fromCharCode(((code - 65 + shift) % 26) + 65);',
      '  } else if (code >= 97 && code <= 122) {',
      '    result += String.fromCharCode(((code - 97 + shift) % 26) + 97);',
      '  } else {',
      '    result += c;',
      '  }',
      '}',
      'console.log(result);',
    ].join('\n'),
    testCases: [
      { input: 'abc\n3', expected: 'def' },
      { input: 'Hola Mundo\n1', expected: 'Ipmb Nvoep' },
      { input: 'xyz\n3', expected: 'abc' },
      { input: 'Hello, World!\n13', expected: 'Uryyb, Jbeyq!' },
    ],
    tags: ['strings', 'charCodeAt', 'cifrado', 'algoritmos'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 25,
    isActive: true,
  },

  // ─────────────────────────────────────────────
  // ADVANCED (5 exercises, 40 points each)
  // ─────────────────────────────────────────────

  {
    title: 'Aplanar array',
    slug: 'js-aplanar-array',
    description:
      'Lee una línea que contiene un array JSON anidado (por ejemplo: [1,[2,[3]],4]). Aplánalo completamente e imprime todos los elementos separados por espacios.',
    difficulty: 'advanced',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Aplanar array',
      '// Lee un array JSON anidado con prompt() y aplánalo.',
      '// Imprime los elementos separados por espacios.',
      '',
      'const input = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const input = prompt();',
      'const arr = JSON.parse(input);',
      'function flatten(a) {',
      '  const result = [];',
      '  for (const item of a) {',
      '    if (Array.isArray(item)) {',
      '      result.push(...flatten(item));',
      '    } else {',
      '      result.push(item);',
      '    }',
      '  }',
      '  return result;',
      '}',
      'console.log(flatten(arr).join(" "));',
    ].join('\n'),
    testCases: [
      { input: '[1,[2,[3]],4]', expected: '1 2 3 4' },
      { input: '[[1,2],[3,[4,[5]]]]', expected: '1 2 3 4 5' },
      { input: '[1,2,3]', expected: '1 2 3' },
      { input: '[[[1]],[[2]],[[3]]]', expected: '1 2 3' },
      { input: '[1,[2,[3,[4,[5]]]]]', expected: '1 2 3 4 5' },
    ],
    tags: ['recursión', 'arrays', 'JSON', 'flatten'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },

  {
    title: 'Paréntesis balanceados',
    slug: 'js-parentesis-balanceados',
    description:
      'Lee una cadena que contiene paréntesis (), corchetes [] y llaves {}. Determina si están correctamente balanceados. Ignora cualquier otro carácter. Imprime "Si" o "No".',
    difficulty: 'advanced',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Paréntesis balanceados',
      '// Lee una cadena con prompt() que puede contener (), [] y {}.',
      '// Imprime "Si" si están balanceados, "No" en caso contrario.',
      '',
      'const input = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const input = prompt();',
      'const stack = [];',
      'const pairs = { ")": "(", "]": "[", "}": "{" };',
      'let balanced = true;',
      'for (const c of input) {',
      '  if ("([{".includes(c)) {',
      '    stack.push(c);',
      '  } else if (")]}".includes(c)) {',
      '    if (stack.length === 0 || stack.pop() !== pairs[c]) {',
      '      balanced = false;',
      '      break;',
      '    }',
      '  }',
      '}',
      'if (stack.length !== 0) balanced = false;',
      'console.log(balanced ? "Si" : "No");',
    ].join('\n'),
    testCases: [
      { input: '({[]})', expected: 'Si' },
      { input: '([)]', expected: 'No' },
      { input: '{[()]}()', expected: 'Si' },
      { input: 'hola(mundo[cruel]{!})', expected: 'Si' },
      { input: '((())', expected: 'No' },
    ],
    tags: ['stack', 'strings', 'algoritmos', 'balanceo'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },

  {
    title: 'Distancia de edición',
    slug: 'js-distancia-edicion',
    description:
      'Lee dos cadenas de texto (una por línea) y calcula la distancia de Levenshtein entre ellas. Esta es el número mínimo de operaciones (inserción, eliminación o sustitución de un carácter) para transformar una cadena en la otra. Imprime el número resultante.',
    difficulty: 'advanced',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Distancia de edición (Levenshtein)',
      '// Lee dos cadenas con prompt() y calcula la distancia de edición.',
      '',
      'const str1 = prompt();',
      'const str2 = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const a = prompt();',
      'const b = prompt();',
      'const m = a.length;',
      'const n = b.length;',
      'const dp = Array.from({ length: m + 1 }, () => Array(n + 1).fill(0));',
      'for (let i = 0; i <= m; i++) dp[i][0] = i;',
      'for (let j = 0; j <= n; j++) dp[0][j] = j;',
      'for (let i = 1; i <= m; i++) {',
      '  for (let j = 1; j <= n; j++) {',
      '    if (a[i - 1] === b[j - 1]) {',
      '      dp[i][j] = dp[i - 1][j - 1];',
      '    } else {',
      '      dp[i][j] = 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);',
      '    }',
      '  }',
      '}',
      'console.log(dp[m][n]);',
    ].join('\n'),
    testCases: [
      { input: 'kitten\nsitting', expected: '3' },
      { input: 'hola\nhola', expected: '0' },
      { input: 'abc\ndef', expected: '3' },
      { input: '\nabc', expected: '3' },
      { input: 'saturday\nsunday', expected: '3' },
    ],
    tags: ['programación-dinámica', 'strings', 'levenshtein', 'algoritmos'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },

  {
    title: 'Permutaciones',
    slug: 'js-permutaciones',
    description:
      'Lee una cadena de texto e imprime todas sus permutaciones únicas, una por línea, en orden lexicográfico. Si la cadena tiene caracteres repetidos, no se deben repetir permutaciones.',
    difficulty: 'advanced',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Permutaciones',
      '// Lee una cadena con prompt() e imprime todas sus permutaciones únicas,',
      '// una por línea, en orden lexicográfico.',
      '',
      'const input = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const input = prompt();',
      'const chars = input.split("").sort();',
      'const results = [];',
      '',
      'function permute(current, remaining) {',
      '  if (remaining.length === 0) {',
      '    results.push(current);',
      '    return;',
      '  }',
      '  for (let i = 0; i < remaining.length; i++) {',
      '    if (i > 0 && remaining[i] === remaining[i - 1]) continue;',
      '    permute(',
      '      current + remaining[i],',
      '      remaining.slice(0, i).concat(remaining.slice(i + 1))',
      '    );',
      '  }',
      '}',
      '',
      'permute("", chars);',
      'for (const r of results) {',
      '  console.log(r);',
      '}',
    ].join('\n'),
    testCases: [
      { input: 'ab', expected: 'ab\nba' },
      { input: 'abc', expected: 'abc\nacb\nbac\nbca\ncab\ncba' },
      { input: 'aab', expected: 'aab\naba\nbaa' },
      { input: 'a', expected: 'a' },
    ],
    tags: ['recursión', 'permutaciones', 'backtracking', 'strings'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },

  {
    title: 'Evaluador de expresiones',
    slug: 'js-evaluador-expresiones',
    description:
      'Lee una expresión matemática como cadena de texto que contiene números enteros, los operadores +, -, * y /, y paréntesis. Evalúa la expresión respetando la precedencia de operadores y paréntesis. La división es entera (truncada hacia cero). Imprime el resultado.',
    difficulty: 'advanced',
    languageSlug: 'javascript',
    starterCode: [
      '// Ejercicio: Evaluador de expresiones',
      '// Lee una expresión matemática con prompt().',
      '// Soporta +, -, *, / (división entera), y paréntesis.',
      '// Imprime el resultado.',
      '',
      'const expr = prompt();',
      '',
      '// Tu código aquí:',
      '',
    ].join('\n'),
    solution: [
      'const expr = prompt().replace(/\\s/g, "");',
      'let pos = 0;',
      '',
      'function parseExpr() {',
      '  let result = parseTerm();',
      '  while (pos < expr.length && (expr[pos] === "+" || expr[pos] === "-")) {',
      '    const op = expr[pos++];',
      '    const term = parseTerm();',
      '    result = op === "+" ? result + term : result - term;',
      '  }',
      '  return result;',
      '}',
      '',
      'function parseTerm() {',
      '  let result = parseFactor();',
      '  while (pos < expr.length && (expr[pos] === "*" || expr[pos] === "/")) {',
      '    const op = expr[pos++];',
      '    const factor = parseFactor();',
      '    result = op === "*" ? result * factor : Math.trunc(result / factor);',
      '  }',
      '  return result;',
      '}',
      '',
      'function parseFactor() {',
      '  if (expr[pos] === "(") {',
      '    pos++;',
      '    const result = parseExpr();',
      '    pos++;',
      '    return result;',
      '  }',
      '  let sign = 1;',
      '  if (expr[pos] === "-") {',
      '    sign = -1;',
      '    pos++;',
      '  }',
      '  let num = 0;',
      '  while (pos < expr.length && expr[pos] >= "0" && expr[pos] <= "9") {',
      '    num = num * 10 + Number(expr[pos]);',
      '    pos++;',
      '  }',
      '  return sign * num;',
      '}',
      '',
      'console.log(parseExpr());',
    ].join('\n'),
    testCases: [
      { input: '3+5*2', expected: '13' },
      { input: '(3+5)*2', expected: '16' },
      { input: '10/3', expected: '3' },
      { input: '2*(3+4*(5-1))', expected: '38' },
      { input: '100-50*2+10', expected: '10' },
    ],
    tags: ['parser', 'recursión', 'expresiones', 'algoritmos-avanzados'],
    timeLimit: 5000,
    memoryLimit: 128,
    points: 40,
    isActive: true,
  },
];
